import { useState } from "preact/hooks";
import { files, modal, runMutation, showToast } from "../../app/store.js";
import { Modal } from "../../components/Primitives.jsx";

const directories=()=>["",...new Set(files.value.map((file)=>file.folder))].sort();
const parentOf=(path)=>path.split("/").slice(0,-1).join("/");
const baseOf=(path)=>path.split("/").pop();

export function FileOpsModals(){const config=modal.value;if(!config)return null;const close=()=>{modal.value=null};if(config.type==="create")return <Create config={config} close={close}/>;if(config.type==="rename")return <Rename config={config} close={close}/>;if(config.type==="move")return <Move config={config} close={close}/>;if(config.type==="delete")return <Delete config={config} close={close}/>;if(config.type==="reorder")return <Reorder config={config} close={close}/>;return null;}

function Create({config,close}){const [dir,setDir]=useState(config.dir||"");const [kind,setKind]=useState("file");const [name,setName]=useState("");const submit=async(event)=>{event.preventDefault();await runMutation("create",{dir,kind,name},`${kind==="file"?"Document":"Folder"} created`,(result)=>runMutation("delete",{path:result.path},"Create undone"));close();};return <Modal title="Create" onClose={close}><form onSubmit={submit}><Field label="Folder"><select value={dir} onChange={(e)=>setDir(e.currentTarget.value)}>{directories().map((path)=><option value={path}>{path||"PM root"}</option>)}</select></Field><Field label="Type"><select value={kind} onChange={(e)=>setKind(e.currentTarget.value)}><option value="file">Markdown document</option><option value="folder">Folder</option></select></Field><Field label="Name"><input autofocus value={name} onInput={(e)=>setName(e.currentTarget.value)}/></Field><button class="button primary" disabled={!name.trim()}>Create</button></form></Modal>;}
function Rename({config,close}){const original=baseOf(config.path).replace(/\.md$/i,"").replace(/^\d+\s*-\s*/,"");const [name,setName]=useState(original);const submit=async(event)=>{event.preventDefault();const result=await runMutation("rename",{path:config.path,name},"Renamed",(result)=>runMutation("rename",{path:result.path,name:original},"Rename undone"));close();if(result.path)location.hash=`/doc/${encodeURI(result.path)}`;};return <Modal title="Rename document" onClose={close}><form onSubmit={submit}><Field label="Name"><input autofocus value={name} onInput={(e)=>setName(e.currentTarget.value)}/></Field><button class="button primary">Rename</button></form></Modal>;}
function Move({config,close}){const original=parentOf(config.path);const [toDir,setToDir]=useState(original);const submit=async(event)=>{event.preventDefault();const result=await runMutation("move",{from:config.path,toDir},"Moved",(result)=>runMutation("move",{from:result.path,toDir:original},"Move undone"));close();if(result.path)location.hash=`/doc/${encodeURI(result.path)}`;};return <Modal title="Move document" onClose={close}><form onSubmit={submit}><Field label="Destination"><select value={toDir} onChange={(e)=>setToDir(e.currentTarget.value)}>{directories().filter((dir)=>dir!==config.path&&!dir.startsWith(`${config.path}/`)).map((path)=><option value={path}>{path||"PM root"}</option>)}</select></Field><button class="button primary" disabled={toDir===original}>Move</button></form></Modal>;}
function Delete({config,close}){const remove=async()=>{const result=await runMutation("delete",{path:config.path},"Moved to PM trash");showToast(`Recoverable at ${result.trashed}`,{action:{label:"Dismiss",run:()=>{}}});close();location.hash="/";};return <Modal title="Move to trash" onClose={close}><p><strong>{config.path}</strong> will be soft-deleted into the PM <code>.trash</code> folder.</p><p class="muted">The server deliberately has no restore mutation. Recovery remains a manual file operation.</p><button class="button" onClick={remove}>Move to trash</button></Modal>;}
function Reorder({config,close}){const initial=files.value.filter((file)=>file.folder===(config.dir||"")&&/^\d+\s*-/.test(baseOf(file.relPath))).map((file)=>baseOf(file.relPath)).sort((a,b)=>Number(a.match(/^\d+/)[0])-Number(b.match(/^\d+/)[0]));const [order,setOrder]=useState(initial);const move=(index,delta)=>{const next=[...order],to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];setOrder(next);};const save=async()=>{await runMutation("reorder",{dir:config.dir||"",order},"Documents reordered",()=>runMutation("reorder",{dir:config.dir||"",order:initial},"Reorder undone"));close();};return <Modal title="Reorder numbered documents" onClose={close}><div class="search-list">{order.map((name,index)=><div class="search-hit" style={{display:"flex",gap:8,alignItems:"center"}}><span style={{flex:1}}>{name}</span><button class="button" onClick={()=>move(index,-1)} disabled={index===0}>↑</button><button class="button" onClick={()=>move(index,1)} disabled={index===order.length-1}>↓</button></div>)}</div><button class="button primary" style={{marginTop:14}} onClick={save}>Save order</button></Modal>;}
const Field=({label,children})=><div class="field"><label>{label}</label>{children}</div>;

