-- ERA Artifacts — let era_actions hold every entity ERA writes, plus deletes.
--
-- Why: era_actions.entity_type was a fixed 6-value CHECK, so anything newer
-- (contacts, shopping items, recurring payments, drafts) was silently
-- rejected and never showed in /era → Artifacts (HUB-89 follow-up).
-- The entity list now lives in code (src/lib/eraArtifacts.ts →
-- ERA_ARTIFACT_ENTITIES) and the API validates against it; the DB keeps a
-- shape check only, so a new feature never needs another migration.
--
-- Run manually in the Supabase SQL Editor (Hard Rule #26 — no agent applies
-- DB changes). Idempotent: safe to run twice.

-- 1. Inspect (optional): the current CHECK constraints on era_actions.
-- select conname, pg_get_constraintdef(oid) from pg_constraint
--  where conrelid = 'public.era_actions'::regclass and contype = 'c';

BEGIN;

-- 2. Drop whatever CHECKs exist on action / entity_type (names were
--    auto-generated by the inline CREATE TABLE in 2026-08-26_era-actions.sql).
DO $$
DECLARE c record;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'public.era_actions'::regclass
       AND contype = 'c'
       AND (pg_get_constraintdef(oid) ILIKE '%entity_type%'
            OR pg_get_constraintdef(oid) ILIKE '%action%')
  LOOP
    EXECUTE format('ALTER TABLE public.era_actions DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

-- 3. New checks: three verbs; entity is a slug (the list lives in code).
ALTER TABLE public.era_actions
  ADD CONSTRAINT era_actions_action_check
  CHECK (action = ANY (ARRAY['created'::text, 'updated'::text, 'deleted'::text]));

ALTER TABLE public.era_actions
  ADD CONSTRAINT era_actions_entity_type_check
  CHECK (entity_type ~ '^[a-z][a-z_]{1,39}$');

COMMIT;

-- 4. Verify: expect exactly these two rows.
-- select conname, pg_get_constraintdef(oid) from pg_constraint
--  where conrelid = 'public.era_actions'::regclass and contype = 'c';

-- Rollback (only if no rows use the new values yet):
-- ALTER TABLE public.era_actions DROP CONSTRAINT era_actions_action_check;
-- ALTER TABLE public.era_actions DROP CONSTRAINT era_actions_entity_type_check;
-- ALTER TABLE public.era_actions ADD CONSTRAINT era_actions_action_check CHECK (action = ANY (ARRAY['created'::text, 'updated'::text]));
-- ALTER TABLE public.era_actions ADD CONSTRAINT era_actions_entity_type_check CHECK (entity_type = ANY (ARRAY['reminder'::text, 'transaction'::text, 'transfer'::text, 'debt'::text, 'meal_plan'::text, 'memory'::text]));
