-- =============================================================================
-- DB STATE SNAPSHOT — the introspection query this repo cannot answer for itself
-- =============================================================================
-- WHAT: Captures everything `migrations/schema.sql` structurally cannot: RLS
--       enablement, full policy bodies, FK cascade rules, triggers, function
--       bodies (incl. SECURITY DEFINER flags) and indexes.
--
-- WHY:  schema.sql is a tables/columns/constraints export. It has no way to
--       express RLS, so every claim in this repo about RLS was previously an
--       unverifiable assertion — and on 2026-08-04 three such claims turned out
--       to be false and cost a production bug (household trips invisible to the
--       partner). See CLAUDE.md Hard Rule #27.
--
-- READ-ONLY. This query writes nothing. It only reads system catalogs, and it
-- deliberately returns NO application row data — table metadata only.
--
-- HOW TO RUN (owner, ~30 seconds):
--   1. Supabase SQL Editor → paste this whole file → Run.
--   2. The result is one column, one row, containing pretty-printed JSON.
--   3. Copy that JSON in full and save it over `migrations/db-state.json`.
--   4. Commit it. The git diff on the next run is your RLS drift report.
--   5. `pnpm db:verify-rls` to sanity-check what you just saved.
--
-- CADENCE: re-run after any migration, and any time an agent needs to reason
-- about RLS, cascades, or SECURITY DEFINER behaviour.
-- =============================================================================

select jsonb_pretty(jsonb_build_object(

  'generated_at', now(),
  'note', 'Generated by migrations/db-state.sql. Catalog metadata only — contains no application row data.',

  -- RLS enablement per table. `rls_forced` matters: when true, even the table
  -- owner is subject to policies, which breaks the SECURITY DEFINER bypass that
  -- several RPCs in this project rely on.
  'tables', coalesce((
    select jsonb_agg(jsonb_build_object(
      'table', c.relname,
      'rls_enabled', c.relrowsecurity,
      'rls_forced', c.relforcerowsecurity
    ) order by c.relname)
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind = 'r'
  ), '[]'::jsonb),

  -- Full policy bodies. `permissive` is load-bearing: a PERMISSIVE policy is
  -- OR'd with its siblings, a RESTRICTIVE one is AND'd and can veto them.
  'policies', coalesce((
    select jsonb_agg(jsonb_build_object(
      'table', tablename,
      'policy', policyname,
      'permissive', permissive,
      'roles', to_jsonb(roles),
      'cmd', cmd,
      'using', qual,
      'with_check', with_check
    ) order by tablename, policyname)
      from pg_policies
     where schemaname = 'public'
  ), '[]'::jsonb),

  -- FK cascade behaviour — what actually happens to children on parent delete.
  'foreign_keys', coalesce((
    select jsonb_agg(jsonb_build_object(
      'table', src.relname,
      'constraint', con.conname,
      'columns', (
        select jsonb_agg(a.attname order by k.ord)
          from unnest(con.conkey) with ordinality k(attnum, ord)
          join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum
      ),
      'references', tgt.relname,
      'on_delete', case con.confdeltype
        when 'a' then 'NO ACTION' when 'r' then 'RESTRICT' when 'c' then 'CASCADE'
        when 'n' then 'SET NULL' when 'd' then 'SET DEFAULT' end,
      'on_update', case con.confupdtype
        when 'a' then 'NO ACTION' when 'r' then 'RESTRICT' when 'c' then 'CASCADE'
        when 'n' then 'SET NULL' when 'd' then 'SET DEFAULT' end
    ) order by src.relname, con.conname)
      from pg_constraint con
      join pg_class src on src.oid = con.conrelid
      join pg_class tgt on tgt.oid = con.confrelid
      join pg_namespace n on n.oid = src.relnamespace
     where con.contype = 'f' and n.nspname = 'public'
  ), '[]'::jsonb),

  'triggers', coalesce((
    select jsonb_agg(jsonb_build_object(
      'table', c.relname,
      'trigger', t.tgname,
      'definition', pg_get_triggerdef(t.oid)
    ) order by c.relname, t.tgname)
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
     where not t.tgisinternal and n.nspname = 'public'
  ), '[]'::jsonb),

  -- Function bodies. `security_definer` identifies the RPCs that bypass RLS —
  -- the single most important thing to know when debugging a visibility bug,
  -- because a SECURITY DEFINER path working while PostgREST fails is near-proof
  -- that RLS is the filter.
  'functions', coalesce((
    select jsonb_agg(jsonb_build_object(
      'name', p.proname,
      'args', pg_get_function_identity_arguments(p.oid),
      'returns', pg_get_function_result(p.oid),
      'security_definer', p.prosecdef,
      'volatility', case p.provolatile
        when 'i' then 'IMMUTABLE' when 's' then 'STABLE' else 'VOLATILE' end,
      'body', p.prosrc
    ) order by p.proname)
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f'
  ), '[]'::jsonb),

  'indexes', coalesce((
    select jsonb_agg(jsonb_build_object(
      'table', tablename, 'index', indexname, 'definition', indexdef
    ) order by tablename, indexname)
      from pg_indexes
     where schemaname = 'public'
  ), '[]'::jsonb)

)) as db_state;
