import { useEffect, useMemo, useState } from "preact/hooks";
import { AGENT_REGISTRY, getAgent } from "../../../../delivery/agent-registry.mjs";
import { ALWAYS_ON_CAPABILITIES, classify } from "../../../../delivery/classify.mjs";
import { scanCheckboxes } from "../../../shared/md-scan.mjs";
import { allTasks, byRelPath, files } from "../../app/store.js";
import { route } from "../../app/router.js";
import { Chip, EmptyState, Modal } from "../../components/Primitives.jsx";
import { Icon } from "../../components/Icon.jsx";
import { deliveryData, deliveryLoading, deliveryPost, deliverEligibility, loadDeliverySessions } from "./deliveryStore.js";

const campaignGlobs={Budget:["src/features/accounts/**","src/features/transactions/**","src/features/categories/**","src/features/recurring/**","src/features/balance/**","src/features/budget/**"],Schedule:["src/features/items/**"],Kitchen:["src/features/recipes/**","src/features/catalogue/**","src/features/inventory/**"],Trips:["src/app/trips/**","src/features/trips/**"],"Hub & ERA":["src/app/chat/**","src/features/hub/**","src/lib/ai/**"],"Notifications & Alerts":["src/app/api/notifications/**","src/app/api/cron/**"]};
const checklist=(path)=>/(?:^|\/)4\s*-\s*Checklist\.md$/i.test(path);

function scopeHints(task){const keywords=task.text.toLowerCase().split(/\s+/).map((word)=>word.replace(/[^\w-]/g,"")).filter((word)=>word.length>3);const globs=[...(campaignGlobs[task.module]||[])];if(/\bapi\b|route|endpoint|cron/i.test(task.text))globs.push("src/app/api/**");return{keywords,globs,modules:[task.module]};}

export function DeliveryHome(){
  const [tab,setTab]=useState("sessions");const [wizard,setWizard]=useState(null);
  useEffect(()=>{loadDeliverySessions();const file=route.value.query.get("file"),cb=Number(route.value.query.get("cb"));if(file&&Number.isInteger(cb)){const task=allTasks.value.find((entry)=>entry.file===file&&entry.cbidx===cb);if(task)setWizard({campaign:task.module,task,provider:"claude",dropped:[],dirtyAck:false});}},[]);
  return <><header class="page-head"><div><div class="eyebrow">Supervised agent workflow</div><h1>Delivery</h1><p>Launch, gate, and inspect implementation sessions while the server remains authoritative.</p></div><button class="button primary" onClick={()=>setWizard({campaign:null,task:null,provider:"claude",dropped:[],dirtyAck:false})}><Icon name="plus"/>New delivery</button></header>{deliveryData.value.buildLockActive&&<div class="lock-banner">A session is already past the plan gate. Other plan approvals wait for the build lock.</div>}<div class="delivery-tabs"><button class={`button ${tab==="sessions"?"primary":""}`} onClick={()=>setTab("sessions")}>Sessions</button><button class={`button ${tab==="agents"?"primary":""}`} onClick={()=>setTab("agents")}>Agent catalog</button></div>{tab==="sessions"?<SessionsList/>:<AgentCatalog/>}{wizard&&<Wizard value={wizard} setValue={setWizard} onClose={()=>setWizard(null)}/>}</>;
}

function SessionsList(){const sessions=deliveryData.value.sessions||[];if(deliveryLoading.value&&!sessions.length)return <div class="empty">Loading sessions…</div>;if(!sessions.length)return <EmptyState icon="bolt" title="No delivery sessions">Launch an open checklist item when you are ready.</EmptyState>;return <div class="session-list">{sessions.map((session)=>{const usage=session.usageTotal?(session.usageTotal.input||0)+(session.usageTotal.output||0):0;return <a class="session-row" href={`#/delivery/session/${session.sessionId}`} style={{color:"inherit"}}><span class={`session-dot ${session.runnerAlive?"alive":""}`}/><Chip tone={session.state==="SHIPPED"?"success":session.state==="BLOCKED"?"blocker":""}>{session.state}</Chip><span class="session-title"><strong>{session.item?.id?`${session.item.id} · `:""}{session.item?.text||"Untitled"}</strong><span class="muted" style={{display:"block",fontSize:11}}>{session.item?.campaign} · {session.agent}</span></span><span class="session-usage mono muted">{usage} tok</span></a>;})}</div>;}

function AgentCatalog(){return <div class="card">{AGENT_REGISTRY.map((agent)=><div class="agent-row"><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><strong>{agent.name}</strong><Chip>{agent.executionMode}</Chip><Chip>{agent.access}</Chip><Chip tone={agent.status==="enabled"?"success":""}>{agent.status} · {agent.phase}</Chip></div><p class="muted" style={{margin:"7px 0 3px"}}>{agent.purpose}</p><div class="eyebrow">trigger: {agent.trigger} · {agent.blocking}</div></div>)}</div>;}

function Wizard({value,setValue,onClose}){
  const topics=[...new Set(files.value.filter((file)=>!file.inFabled&&checklist(file.relPath)).map((file)=>file.module))];
  const candidates=value.campaign?allTasks.value.filter((task)=>task.module===value.campaign&&!task.inFabled&&checklist(task.file)):[];
  const capabilities=value.task?classify({item:{text:value.task.text,campaign:value.task.module},scopeHints:scopeHints(value.task)}):[];
  const update=(patch)=>setValue({...value,...patch});
  const launch=async()=>{const file=byRelPath.value.get(value.task.file.toLowerCase());const line=scanCheckboxes(file.raw)[value.task.cbidx]?.line;const expectText=line==null?value.task.text:file.raw.split("\n")[line];const result=await deliveryPost("start",{file:value.task.file,cbidx:value.task.cbidx,expectText,agent:value.provider,dirtyAck:value.dirtyAck,options:{capabilitiesDrop:value.dropped}},"Delivery session launched");onClose();location.hash=`/delivery/session/${result.sessionId}`;};
  return <Modal title="New delivery session" onClose={onClose}><div class="wizard-steps"><div class={`wizard-step ${!value.campaign?"active":""}`}><div class="eyebrow">1 · Topic</div><div class="chip-row">{topics.map((topic)=><button class={`button ${value.campaign===topic?"primary":""}`} onClick={()=>update({campaign:topic,task:null,dropped:[]})}>{topic}</button>)}</div></div>{value.campaign&&<div class={`wizard-step ${!value.task?"active":""}`}><div class="eyebrow">2 · Work item</div><div class="search-list" style={{maxHeight:250,overflow:"auto"}}>{candidates.map((task)=>{const eligibility=deliverEligibility(task,deliveryData.value.sessions,topics);return <button class={`palette-result ${value.task?.key===task.key?"selected":""}`} disabled={!eligibility.eligible} title={eligibility.reason||""} onClick={()=>update({task,dropped:[]})}><span class="palette-result-main"><strong>{task.idChip?`${task.idChip} · `:""}{task.text}</strong><span>{task.section} · {eligibility.reason||"ready"}</span></span></button>;})}</div></div>}{value.task&&<><div class="wizard-step active"><div class="eyebrow">3 · Preview</div><p>{value.task.text}</p><span class="mono muted" style={{fontSize:11}}>{value.task.file} · cb {value.task.cbidx}</span></div><div class="wizard-step"><div class="eyebrow">4 · Provider</div><div class="chip-row">{["claude","codex"].map((provider)=><button class={`button ${value.provider===provider?"primary":""}`} onClick={()=>update({provider})}>{provider}</button>)}</div></div><div class="wizard-step"><div class="eyebrow">5 · Capabilities <span class="muted">preview — server is authoritative</span></div><div class="chip-row">{capabilities.map((cap)=>{const locked=ALWAYS_ON_CAPABILITIES.includes(cap.name),dropped=value.dropped.includes(cap.name),agent=getAgent(cap.name);return <button class={`chip capability ${dropped?"dropped":""}`} disabled={locked} title={agent?.purpose} onClick={()=>update({dropped:dropped?value.dropped.filter((name)=>name!==cap.name):[...value.dropped,cap.name]})}>{agent?.name||cap.name}{locked?" 🔒":dropped?" · restore":" · remove"}</button>;})}</div></div><label class="wizard-step"><input type="checkbox" checked={value.dirtyAck} onChange={(event)=>update({dirtyAck:event.currentTarget.checked})}/> I understand agent edits will interleave with uncommitted changes.</label><button class="button primary" onClick={launch} disabled={!value.dirtyAck}><Icon name="bolt"/>Launch session</button></>}</div></Modal>;
}
