import { useEffect, useState } from "preact/hooks";
import { route } from "../../app/router.js";
import { showToast } from "../../app/store.js";
import { apiGet } from "../../app/api.js";
import { Chip, EmptyState } from "../../components/Primitives.jsx";
import { Breadcrumbs } from "../nav/Breadcrumbs.jsx";
import { deliveryEvents, deliveryPost, deliverySession, loadDeliverySession } from "./deliveryStore.js";

const steps=["SELECTED","REFINING","SPEC_READY","PLAN_READY","BUILDING","VALIDATING","REVIEWING","UAT_READY","ACCEPTED","SHIPPED"];
const terminal=new Set(["SHIPPED","CANCELLED","FAILED"]);
const gateArtifact={spec:"spec.md",plan:"plan.md",uat:"uat/summary.md"};

export function SessionDetail(){
  const id=route.value.id;const [artifact,setArtifact]=useState(null);const [artifactError,setArtifactError]=useState("");
  useEffect(()=>{loadDeliverySession(id,{reset:true}).catch((error)=>showToast(error.message,{type:"error"}));},[id]);
  const detail=deliverySession.value;if(!detail)return <div class="empty">Loading session…</div>;
  const {packet,state,artifacts,runner}=detail;const current=steps.indexOf(state.state);const usage=state.usage?.total||{};
  const openArtifact=async(path)=>{setArtifact({name:path,content:"Loading…"});setArtifactError("");try{setArtifact(await apiGet(`/api/delivery/artifact?id=${encodeURIComponent(id)}&path=${encodeURIComponent(path)}`));}catch(error){setArtifactError(error.message);}};
  return <><Breadcrumbs items={[{label:"Delivery",href:"/delivery"},{label:id}]}/><header class="page-head" style={{marginTop:18}}><div><div class="eyebrow">{packet.item.campaign} · {packet.agent}</div><h1>{packet.item.id?`${packet.item.id} — `:""}{packet.item.text}</h1><div class="chip-row"><Chip>{state.state}</Chip><Chip>{runner.alive?"runner alive":"runner stale"}</Chip><Chip>{(usage.input||0)+(usage.output||0)} tok</Chip>{!runner.alive&&!terminal.has(state.state)&&<button class="button" onClick={()=>deliveryPost("resume",{id},"Resume requested").then(()=>loadDeliverySession(id))}>Resume</button>}</div></div></header>
    <div class="stepper">{steps.map((step,index)=><div class={`step-node ${index<current?"done":index===current?"current":""}`}>{step}</div>)}</div>
    {state.awaiting&&<GatePanel id={id} state={state} openArtifact={openArtifact}/>}<div class="delivery-grid" style={{marginTop:18}}><div><section class="card"><h2>Timeline</h2><div class="timeline">{deliveryEvents.value.length?deliveryEvents.value.map((event)=><div class="event"><span class="mono muted">{new Date(event.ts).toLocaleTimeString()}</span> <strong>{event.type}</strong>{event.phase&&<Chip>{event.phase}</Chip>}</div>):<div class="empty">No events yet.</div>}</div></section>{!terminal.has(state.state)&&<MessageComposer id={id}/>}</div><aside><section class="card"><h2>Artifacts</h2>{artifacts.length?artifacts.map((entry)=><button class="nav-link" onClick={()=>openArtifact(entry.path)}>{entry.path}<span class="count">{entry.size} B</span></button>):<div class="empty">No artifacts yet.</div>}</section><UsageMeter usage={state.usage}/></aside></div>
    {artifact&&<div class="modal-backdrop" onMouseDown={(event)=>event.target===event.currentTarget&&setArtifact(null)}><section class="modal artifact-viewer" style={{width:"min(1000px,96vw)"}}><div class="page-head"><h2>{artifact.name}</h2><button class="icon-button" onClick={()=>setArtifact(null)}>×</button></div>{artifactError?<div class="empty">{artifactError}</div>:<pre><code>{artifact.lang==="json"?pretty(artifact.content):artifact.content}</code></pre>}</section></div>}</>;
}

function GatePanel({id,state,openArtifact}){
  const gate=state.awaiting.gate;const [note,setNote]=useState("");const [confirmText,setConfirmText]=useState("");const [answer,setAnswer]=useState("");const [tick,setTick]=useState(true);
  useEffect(()=>{if(gateArtifact[gate])openArtifact(gateArtifact[gate]);},[gate]);
  const decide=async(decision)=>{const body={id,gate,decision,note:note||null};if(gate==="plan"&&decision==="approve")body.confirmText=confirmText;if(gate==="uat"&&decision==="accept")body.tickCheckbox=tick;if(gate==="question")body.answer=answer;await deliveryPost("decision",body,"Decision recorded");await loadDeliverySession(id);};
  return <section class="card" style={{marginTop:18,borderColor:"var(--era-border-active)"}}><div class="eyebrow">Owner gate</div><h2>{gate}</h2>{gate==="question"&&state.awaiting.questions&&<ul>{state.awaiting.questions.map((question)=><li>{question.text}</li>)}</ul>}{gate==="blocked"&&<p class="verdict-block">{state.lastError?.message||"Session is blocked."}</p>}{["spec","plan","uat"].includes(gate)&&<button class="button" onClick={()=>openArtifact(gateArtifact[gate])}>Open {gateArtifact[gate]}</button>}{gate==="plan"&&<div class="field"><label>Typed approval when risk-flagged</label><input value={confirmText} onInput={(event)=>setConfirmText(event.currentTarget.value)} placeholder="APPROVE"/></div>}{gate==="question"&&<div class="field"><label>Answer</label><textarea value={answer} onInput={(event)=>setAnswer(event.currentTarget.value)}/></div>}{["spec","plan","uat"].includes(gate)&&<div class="field"><label>Owner note / requested change</label><textarea value={note} onInput={(event)=>setNote(event.currentTarget.value)}/></div>}{gate==="uat"&&<label class="button"><input type="checkbox" checked={tick} onChange={(event)=>setTick(event.currentTarget.checked)}/>Tick source checkbox on accept</label>}<div class="chip-row" style={{marginTop:12}}>{["spec","plan"].includes(gate)&&<><button class="button primary" onClick={()=>decide("approve")}>Approve</button><button class="button" onClick={()=>decide("reject")}>Request changes</button></>}{gate==="uat"&&<><button class="button primary" onClick={()=>decide("accept")}>Accept</button><button class="button" onClick={()=>decide("reject")}>Request changes</button></>}{gate==="question"&&<button class="button primary" onClick={()=>decide("answer")}>Submit answer</button>}{gate==="blocked"&&<button class="button primary" onClick={()=>decide("retry")}>Retry</button>}{gate==="shipped"&&<button class="button primary" onClick={()=>decide("shipped")}>Mark shipped</button>}<button class="button ghost" onClick={()=>deliveryPost("decision",{id,gate,decision:"cancel",note},"Session cancelled").then(()=>loadDeliverySession(id))}>Cancel session</button></div></section>;
}

function MessageComposer({id}){const [text,setText]=useState("");const send=async()=>{if(!text.trim())return;await deliveryPost("message",{id,text:text.trim()},"Message queued for the next boundary");setText("");};return <section class="card" style={{marginTop:18}}><h2>Message the orchestrator</h2><div class="field"><textarea rows="4" value={text} onInput={(event)=>setText(event.currentTarget.value)} placeholder="Guidance is read at the next step boundary."/></div><button class="button" onClick={send}>Queue message</button></section>;}

function UsageMeter({usage={}}){const phases=Object.entries(usage.perPhase||{});return <section class="card" style={{marginTop:18}}><h2>Usage</h2><div class="stat-value">{(usage.total?.input||0)+(usage.total?.output||0)}</div><div class="muted">total tokens</div>{phases.length>0&&<table class="usage-table"><thead><tr><th>Phase</th><th>Input</th><th>Output</th></tr></thead><tbody>{phases.map(([phase,row])=><tr><td>{phase}</td><td>{row.input||0}</td><td>{row.output||0}</td></tr>)}</tbody></table>}</section>;}
function pretty(text){try{return JSON.stringify(JSON.parse(text),null,2);}catch{return text;}}

